# Generated by Django 4.0.6 on 2022-07-31 06:44

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customimage_article_frontimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='frontImage',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.DeleteModel(
            name='CustomImage',
        ),
    ]
