# Generated by Django 4.0.6 on 2022-07-31 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0006_alter_article_frontimage_delete_customimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='frontImage',
            field=models.ForeignKey(help_text='Header background image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
